### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by JagnDC** [HakanSeven12/Delaunator-Python#1]
Hello, When I run test.py, it has a problem. Could you solve this problem? Thank u 
```
Traceback (most recent call last):
  File ".\Test.py", line 12, in <module>
    triangles = Delaunator(points).triangles
  File "D:\Workplace\bigdata\Delaunator-Python-master\Delaunator.py", line 19, in __init__
    triangles = self.constructor(coords)
  File "D:\Workplace\bigdata\Delaunator-Python-master\Delaunator.py", line 41, in constructor
    triangles = self.update(coords)
  File "D:\Workplace\bigdata\Delaunator-Python-master\Delaunator.py", line 237, in update
    t = self._addTriangle(q, i, e, -1, self.hullTri[e], self.hullTri[q])
  File "D:\Workplace\bigdata\Delaunator-Python-master\Delaunator.py", line 361, in _addTriangle
    self._triangles[t] = i0
IndexError: list assignment index out of range
```

**Comment by HakanSeven12** [comment]
I don't get this error. do you see this one time or every time?

**Comment by HakanSeven12** [comment]
If you are using it on freecad use this

`points = np.random.randint(1,1677.7215,size=(10000,2))`

Test.py updated

**Comment by JagnDC** [comment]
I'm sorry that I didn't reply in time. I tried to turn the value down, and test will run. Maybe my laptop is out of memory.
Anyway, your code is great. Thank you~

**Comment by HakanSeven12** [comment]
You are welcome :)
