### ISSUE TITLE
Divide by Zero Error

### ISSUE THREAD

**Issue by aryamansharda** [HakanSeven12/Delaunator-Python#5]
Hi,

When I run the starter code, I get a divide by zero error: 
```
from Delaunator import Delaunator
points = [[168, 180], [168, 178], [168, 179], [168, 181], [168, 23], [168, 23]]

triangles = Delaunator(points).triangles
print(triangles)
```

and the output is:

```
aryamansharda@Aryamans-MacBook-Pro Delaunay % python3 LowPolygonArt.py
Traceback (most recent call last):
  File "LowPolygonArt.py", line 19, in <module>
    triangles = Delaunator(points).triangles
  File "/Users/aryamansharda/Downloads/Delaunay/Delaunator.py", line 19, in __init__
    triangles = self.constructor(coords)
  File "/Users/aryamansharda/Downloads/Delaunay/Delaunator.py", line 41, in constructor
    triangles = self.update(coords)
  File "/Users/aryamansharda/Downloads/Delaunay/Delaunator.py", line 100, in update
    r = circumradius(i0x, i0y, i1x, i1y, coords[2 * i], coords[2 * i + 1])
  File "/Users/aryamansharda/Downloads/Delaunay/Delaunator.py", line 427, in circumradius
    d = 0.5/(dx * ey - dy * ex)
ZeroDivisionError: float division by zero
```

**Comment by HakanSeven12** [comment]
You have two same point at the list and that caused the issue.
